# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - help wanted
  - Backer Requested
  - good first issue
  - starters
  - bug
  - cla-signed
  - cla-already-signed
  - proposal
  - contributor-experience
  - developer-experience
  
# Label to use when marking an issue as stale
staleLabel: waiting-for-response-or-contribution

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If you want this issue progressed faster please start a conversation about raising a pull-request or [coordinating your pull-request with a maintainer](https://reactiveui.net/slack) to get it merged. Understand that [if folks like yourself don't contribute, ReactiveUI won't grow](https://reactiveui.net/blog/2018/05/reactiveui-succession). You may or may not know this but ReactiveUI is maintained by unpaid volunteers. The maintainers put up a big marketing front but at it's core is a couple of passionate folks. ReactiveUI cares about open-source sustainability as maintainers have a serious load on their shoulders. Consumers shouldn't be naive in thinking that the latest update to a nuget package just magically materializes from the ethers. These things happen because our peers make them happen. No-one wants a tragedy of the commons situation. I urge you to get involved. Thank-you.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
