queue: "Hosted VS2017"

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.6.2
  inputs:
    versionSpec: 4.6.2

- powershell: |
    nuget install SignClient -Version 0.9.1 -SolutionDir $(Build.SourcesDirectory) -Verbosity quiet -ExcludeVersion
    .\build.cmd
  displayName: Build 
  env:
    SIGNCLIENT_SECRET: $(SignClientSecret)
    SIGNCLIENT_USER: $(SignClientUser)
    

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: artifacts/*.nupkg
    artifactType: container
    artifactName: Packages
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    pathToPublish: '**/*.binlog'
    artifactType: container
    artifactName: Logs
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: Publish Binaries
  inputs:
    pathToPublish: '**/bin/*'
    artifactType: container
    artifactName: Binaries
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: Publish Generated Events
  inputs:
    pathToPublish: src/ReactiveUI.**/Events_*.cs
    artifactType: container
    artifactName: Events
  condition: always()