//------------------------------------------------------------------------------
// <auto-generated>
//     The version identifiers are automatically updated via the build script.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ReactiveUI")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyCopyright("Copyright (c) ReactiveUI and contributors")]

