// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Pex.Framework.Generated;

namespace ReactiveUI.Serialization.Tests
{
    public partial class ModelBaseTest
    {
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent78702()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void GuidsShouldBeUniqueForContentThrowsNullReferenceException361()
{
    string[] ss = new string[13];
    ss[0] = "";
    ss[1] = "";
    ss[2] = "";
    ss[3] = "";
    ss[4] = "";
    ss[5] = "";
    ss[6] = "";
    ss[7] = "";
    ss[8] = "";
    ss[9] = "";
    ss[10] = "";
    ss[11] = "";
    ss[12] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent29901()
{
    string[] ss = new string[0];
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent46801()
{
    string[] ss = new string[3];
    ss[0] = "";
    ss[1] = "";
    ss[2] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
    }
}
