// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Pex.Framework.Generated;

namespace ReactiveUI.Serialization.Tests
{
    public partial class ModelBaseTest
    {
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void GuidsShouldBeUniqueForContentThrowsNullReferenceException901()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent78701()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void GuidsShouldBeUniqueForContentThrowsNullReferenceException638()
{
    string[] ss = new string[5];
    ss[0] = "\udc00";
    ss[1] = "\udc00";
    ss[2] = "\udc00";
    ss[3] = "\udc00";
    ss[4] = "\udc00";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent23702()
{
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void GuidsShouldBeUniqueForContentThrowsNullReferenceException975()
{
    string[] ss = new string[5];
    ss[0] = "\ud801\udc00";
    ss[1] = "\ud801\udc00";
    ss[2] = "\ud801\udc00";
    ss[3] = "\ud801\udc00";
    ss[4] = "\ud801\udc00";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent78702()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent237()
{
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent368()
{
    string[] ss = new string[3];
    ss[0] = "";
    ss[1] = "";
    ss[2] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent535()
{
    string[] ss = new string[0];
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent634()
{
    string[] ss = new string[5];
    ss[0] = "\ud800\0\0\0\0";
    ss[1] = "\ud800\0\0\0\0";
    ss[2] = "\ud800\0\0\0\0";
    ss[3] = "\ud800\0\0\0\0";
    ss[4] = "\ud800\0\0\0\0";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent728()
{
    string[] ss = new string[13];
    ss[0] = "";
    ss[1] = "";
    ss[2] = "";
    ss[3] = "";
    ss[4] = "";
    ss[5] = "";
    ss[6] = "";
    ss[7] = "";
    ss[8] = "";
    ss[9] = "";
    ss[10] = "";
    ss[11] = "";
    ss[12] = "";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent12801()
{
    string[] ss = new string[5];
    ss[0] = "\ud801\udc00";
    ss[1] = "\ud801\udc00";
    ss[2] = "\ud801\udc00";
    ss[3] = "\ud801\udc00";
    ss[4] = "\ud801\udc00";
    this.GuidsShouldBeUniqueForContent(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void GuidsShouldBeUniqueForContent665()
{
    string[] ss = new string[5];
    ss[0] = "\u0080";
    ss[1] = "\u0080";
    ss[2] = "\u0080";
    ss[3] = "\u0080";
    ss[4] = "\u0080";
    this.GuidsShouldBeUniqueForContent(ss);
}
    }
}
