// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Pex.Framework.Generated;

namespace ReactiveUI.Serialization.Tests
{
    public partial class ModelBaseTest
    {
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void ItemsChangedShouldFire237()
{
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    this.ItemsChangedShouldFire(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void ItemsChangedShouldFire923()
{
    string[] ss = new string[2];
    ss[0] = "\0\0\0";
    ss[1] = "\0\0\0\0\0\0\0";
    this.ItemsChangedShouldFire(ss);
}
[Fact]
[PexGeneratedBy(typeof(ModelBaseTest))]
public void ItemsChangedShouldFire368()
{
    string[] ss = new string[3];
    ss[0] = "";
    ss[1] = "";
    ss[2] = "";
    this.ItemsChangedShouldFire(ss);
}
    }
}
