// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

namespace ReactiveUI.Serialization.Tests
{
    public partial class SerializedCollectionTest
    {
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException432()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException987()
{
    string[] ss = new string[2];
    ss[0] = "\uc080";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
public void AddingItemsShouldChangeTheContentHash4701()
{
    string[] ss = new string[0];
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException746()
{
    string[] ss = new string[2];
    ss[0] = "\0";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException426()
{
    string[] ss = new string[1];
    ss[0] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException365()
{
    string[] ss = new string[2];
    ss[0] = "\0\ud800\udc00\0\0\0\0\0\0\0\0\0\0\0\0";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException190()
{
    string[] ss = new string[2];
    ss[0] = "\0\u0880\0\0\0\0\0\0\0\0\0\0\0\0\0";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException450()
{
    string[] ss = new string[2];
    ss[0] = "\0\u0080\0\0\0\0\0\0\0\0\0\0\0\0\0";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException934()
{
    string[] ss = new string[2];
    ss[0] = "\0\udc00\0\0\0\0\0\0\0\0\0\0\0\0\0";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException800()
{
    string[] ss = new string[2];
    ss[0] = "\ud800";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void AddingItemsShouldChangeTheContentHashThrowsPexAssertFailedException984()
{
    string[] ss = new string[2];
    ss[0] = "\u0080";
    ss[1] = "";
    this.AddingItemsShouldChangeTheContentHash(ss);
}
    }
}
