// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Pex.Framework.Generated;

namespace ReactiveUI.Serialization.Tests
{
    public partial class SerializedCollectionTest
    {
[Fact]
[PexGeneratedBy(typeof(SerializedCollectionTest))]
public void RemovingItemsShouldChangeTheContentHash37201()
{
    string[] ss = new string[2];
    int[] ints = new int[1];
    ss[1] = "";
    ints[0] = 1;
    this.RemovingItemsShouldChangeTheContentHash(ss, ints);
}
    }
}
