// Copyright (c) 2009-2026 .NET Foundation and Contributors. All rights reserved.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <auto-generated/>

#nullable enable

namespace System.Reactive.Disposables;

/// <summary>
/// Provides extension methods associated with the <see cref="CompositeDisposable"/>.
/// </summary>
public static class DisposableMixins
{
    /// <summary>
    /// Ensures the provided disposable is disposed with the specified <see cref="CompositeDisposable"/>.
    /// </summary>
    /// <typeparam name="T">The type of the disposable.</typeparam>
    /// <param name="item">The disposable to add to the composite.</param>
    /// <param name="compositeDisposable">The composite the disposable is added to.</param>
    /// <returns>The <paramref name="item"/>, to allow fluent use.</returns>
    public static T DisposeWith<T>(this T item, CompositeDisposable compositeDisposable)
        where T : IDisposable
    {
        ArgumentExceptionHelper.ThrowIfNull(compositeDisposable);
        compositeDisposable.Add(item);
        return item;
    }
}
