// Copyright (c) 2009-2026 .NET Foundation and Contributors. All rights reserved.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <auto-generated/>

#nullable enable

namespace System.Reactive.Subjects;

/// <summary>
/// Represents an object that is both an observable sequence as well as an observer.
/// </summary>
/// <typeparam name="TSource">The type of the elements processed by the subject.</typeparam>
/// <typeparam name="TResult">The type of the elements produced by the subject.</typeparam>
public interface ISubject<in TSource, out TResult> : IObserver<TSource>, IObservable<TResult>
{
}

/// <summary>
/// Represents an object that is both an observable sequence as well as an observer.
/// </summary>
/// <typeparam name="T">The type of the elements processed by the subject.</typeparam>
public interface ISubject<T> : ISubject<T, T>
{
}
