// Copyright (c) 2009-2026 .NET Foundation and Contributors. All rights reserved.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <auto-generated/>

#nullable enable

using ReactiveUI.Internal;

namespace System.Reactive.Concurrency;

/// <summary>
/// Temporary migration shim. A scheduler whose scheduling methods are not yet implemented; provided so code that
/// references the System.Reactive scheduler types compiles while the owned scheduler layer is built out.
/// </summary>
public abstract class UnimplementedScheduler : IScheduler
{
    private const string NotImplementedMessage =
        "Scheduling is not implemented yet during the System.Reactive removal. This is a temporary migration shim.";

    /// <inheritdoc/>
    public DateTimeOffset Now => DateTimeOffset.Now;

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, Func<IScheduler, TState, IDisposable> action) =>
        throw new NotImplementedException(NotImplementedMessage);

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, TimeSpan dueTime, Func<IScheduler, TState, IDisposable> action) =>
        throw new NotImplementedException(NotImplementedMessage);

    /// <inheritdoc/>
    public IDisposable Schedule<TState>(TState state, DateTimeOffset dueTime, Func<IScheduler, TState, IDisposable> action) =>
        throw new NotImplementedException(NotImplementedMessage);
}

/// <summary>Temporary migration shim for <c>CurrentThreadScheduler</c>.</summary>
public sealed class CurrentThreadScheduler : UnimplementedScheduler
{
    /// <summary>Gets the singleton instance.</summary>
    public static CurrentThreadScheduler Instance { get; } = new();
}

/// <summary>Temporary migration shim for <c>TaskPoolScheduler</c>.</summary>
public sealed class TaskPoolScheduler : UnimplementedScheduler
{
    /// <summary>Gets the default instance.</summary>
    public static TaskPoolScheduler Default { get; } = new();
}

/// <summary>Temporary migration shim for <c>DefaultScheduler</c>.</summary>
public sealed class DefaultScheduler : UnimplementedScheduler
{
    /// <summary>Gets the singleton instance.</summary>
    public static DefaultScheduler Instance { get; } = new();
}

/// <summary>Temporary migration shim for <c>ImmediateScheduler</c>.</summary>
public sealed class ImmediateScheduler : UnimplementedScheduler
{
    /// <summary>Gets the singleton instance.</summary>
    public static ImmediateScheduler Instance { get; } = new();
}

/// <summary>
/// Temporary migration shims for the System.Reactive <see cref="IScheduler"/> convenience extension methods (which
/// are not declared on the interface). They forward to the stateful <c>Schedule&lt;TState&gt;</c> members.
/// </summary>
public static class SchedulerExtensions
{
    /// <summary>Schedules an action to be executed.</summary>
    /// <param name="scheduler">The scheduler to run the action on.</param>
    /// <param name="action">The action to execute.</param>
    /// <returns>A disposable used to cancel the scheduled action.</returns>
    public static IDisposable Schedule(this IScheduler scheduler, Action action)
    {
        ArgumentExceptionHelper.ThrowIfNull(scheduler);
        ArgumentExceptionHelper.ThrowIfNull(action);
        return scheduler.Schedule(action, static (_, a) =>
        {
            a();
            return EmptyDisposable.Instance;
        });
    }

    /// <summary>Schedules an action to be executed after the specified relative time.</summary>
    /// <param name="scheduler">The scheduler to run the action on.</param>
    /// <param name="dueTime">The relative time after which to execute the action.</param>
    /// <param name="action">The action to execute.</param>
    /// <returns>A disposable used to cancel the scheduled action.</returns>
    public static IDisposable Schedule(this IScheduler scheduler, TimeSpan dueTime, Action action)
    {
        ArgumentExceptionHelper.ThrowIfNull(scheduler);
        ArgumentExceptionHelper.ThrowIfNull(action);
        return scheduler.Schedule(action, dueTime, static (_, a) =>
        {
            a();
            return EmptyDisposable.Instance;
        });
    }

    /// <summary>Schedules an action to be executed at the specified absolute time.</summary>
    /// <param name="scheduler">The scheduler to run the action on.</param>
    /// <param name="dueTime">The absolute time at which to execute the action.</param>
    /// <param name="action">The action to execute.</param>
    /// <returns>A disposable used to cancel the scheduled action.</returns>
    public static IDisposable Schedule(this IScheduler scheduler, DateTimeOffset dueTime, Action action)
    {
        ArgumentExceptionHelper.ThrowIfNull(scheduler);
        ArgumentExceptionHelper.ThrowIfNull(action);
        return scheduler.Schedule(action, dueTime, static (_, a) =>
        {
            a();
            return EmptyDisposable.Instance;
        });
    }
}

/// <summary>Temporary migration shim for the static <c>Scheduler</c> entry points.</summary>
public static class Scheduler
{
    /// <summary>Gets the immediate scheduler.</summary>
    public static IScheduler Immediate => ImmediateScheduler.Instance;

    /// <summary>Gets the current-thread scheduler.</summary>
    public static IScheduler CurrentThread => CurrentThreadScheduler.Instance;

    /// <summary>Gets the default scheduler.</summary>
    public static IScheduler Default => DefaultScheduler.Instance;

    /// <summary>Gets the task-pool scheduler.</summary>
    public static IScheduler TaskPool => TaskPoolScheduler.Default;
}
