#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidPlayground.Resource", IsApplication=true)]

namespace AndroidPlayground
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int actionBarDivider = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int actionBarItemBackground = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int actionBarSize = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int actionBarSplitStyle = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int actionBarStyle = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int actionBarTabBarStyle = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int actionBarTabStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int actionBarTabTextStyle = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int actionBarWidgetTheme = 2130771980;
			
			// aapt resource value: 0x7f01003a
			public const int actionButtonStyle = 2130772026;
			
			// aapt resource value: 0x7f010039
			public const int actionDropDownStyle = 2130772025;
			
			// aapt resource value: 0x7f010010
			public const int actionMenuTextAppearance = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int actionMenuTextColor = 2130771985;
			
			// aapt resource value: 0x7f010014
			public const int actionModeBackground = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int actionModeCloseButtonStyle = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int actionModeCloseDrawable = 2130771990;
			
			// aapt resource value: 0x7f010018
			public const int actionModePopupWindowStyle = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int actionModeShareDrawable = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int actionModeSplitBackground = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int actionModeStyle = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int actionOverflowButtonStyle = 2130771977;
			
			// aapt resource value: 0x7f01003f
			public const int actionSpinnerItemStyle = 2130772031;
			
			// aapt resource value: 0x7f010047
			public const int activatedBackgroundIndicator = 2130772039;
			
			// aapt resource value: 0x7f010046
			public const int activityChooserViewStyle = 2130772038;
			
			// aapt resource value: 0x7f010002
			public const int background = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int backgroundSplit = 2130771971;
			
			// aapt resource value: 0x7f01004e
			public const int backgroundStacked = 2130772046;
			
			// aapt resource value: 0x7f010019
			public const int buttonStyleSmall = 2130771993;
			
			// aapt resource value: 0x7f01004f
			public const int customNavigationLayout = 2130772047;
			
			// aapt resource value: 0x7f010049
			public const int displayOptions = 2130772041;
			
			// aapt resource value: 0x7f010005
			public const int divider = 2130771973;
			
			// aapt resource value: 0x7f010038
			public const int dividerVertical = 2130772024;
			
			// aapt resource value: 0x7f01003c
			public const int dropDownListViewStyle = 2130772028;
			
			// aapt resource value: 0x7f01003e
			public const int dropdownListPreferredItemHeight = 2130772030;
			
			// aapt resource value: 0x7f01005e
			public const int expandActivityOverflowButtonDrawable = 2130772062;
			
			// aapt resource value: 0x7f010058
			public const int headerBackground = 2130772056;
			
			// aapt resource value: 0x7f010004
			public const int height = 2130771972;
			
			// aapt resource value: 0x7f01003b
			public const int homeAsUpIndicator = 2130772027;
			
			// aapt resource value: 0x7f010050
			public const int homeLayout = 2130772048;
			
			// aapt resource value: 0x7f010056
			public const int horizontalDivider = 2130772054;
			
			// aapt resource value: 0x7f01004c
			public const int icon = 2130772044;
			
			// aapt resource value: 0x7f01005f
			public const int iconifiedByDefault = 2130772063;
			
			// aapt resource value: 0x7f010052
			public const int indeterminateProgressStyle = 2130772050;
			
			// aapt resource value: 0x7f01005d
			public const int initialActivityCount = 2130772061;
			
			// aapt resource value: 0x7f010059
			public const int itemBackground = 2130772057;
			
			// aapt resource value: 0x7f01005b
			public const int itemIconDisabledAlpha = 2130772059;
			
			// aapt resource value: 0x7f010054
			public const int itemPadding = 2130772052;
			
			// aapt resource value: 0x7f010055
			public const int itemTextAppearance = 2130772053;
			
			// aapt resource value: 0x7f010045
			public const int listPopupWindowStyle = 2130772037;
			
			// aapt resource value: 0x7f010032
			public const int listPreferredItemHeightSmall = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int listPreferredItemPaddingLeft = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int listPreferredItemPaddingRight = 2130772020;
			
			// aapt resource value: 0x7f01004d
			public const int logo = 2130772045;
			
			// aapt resource value: 0x7f010048
			public const int navigationMode = 2130772040;
			
			// aapt resource value: 0x7f01003d
			public const int popupMenuStyle = 2130772029;
			
			// aapt resource value: 0x7f01005c
			public const int preserveIconSpacing = 2130772060;
			
			// aapt resource value: 0x7f010053
			public const int progressBarPadding = 2130772051;
			
			// aapt resource value: 0x7f010051
			public const int progressBarStyle = 2130772049;
			
			// aapt resource value: 0x7f010060
			public const int queryHint = 2130772064;
			
			// aapt resource value: 0x7f010024
			public const int searchAutoCompleteTextView = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int searchDropdownBackground = 2130772005;
			
			// aapt resource value: 0x7f01002f
			public const int searchResultListItemHeight = 2130772015;
			
			// aapt resource value: 0x7f010026
			public const int searchViewCloseIcon = 2130772006;
			
			// aapt resource value: 0x7f01002a
			public const int searchViewEditQuery = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int searchViewEditQueryBackground = 2130772011;
			
			// aapt resource value: 0x7f010027
			public const int searchViewGoIcon = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int searchViewSearchIcon = 2130772008;
			
			// aapt resource value: 0x7f01002c
			public const int searchViewTextField = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int searchViewTextFieldRight = 2130772013;
			
			// aapt resource value: 0x7f010029
			public const int searchViewVoiceIcon = 2130772009;
			
			// aapt resource value: 0x7f01001a
			public const int selectableItemBackground = 2130771994;
			
			// aapt resource value: 0x7f010023
			public const int spinnerDropDownItemStyle = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int spinnerItemStyle = 2130772002;
			
			// aapt resource value: 0x7f01004b
			public const int subtitle = 2130772043;
			
			// aapt resource value: 0x7f010001
			public const int subtitleTextStyle = 2130771969;
			
			// aapt resource value: 0x7f01001c
			public const int textAppearanceLargePopupMenu = 2130771996;
			
			// aapt resource value: 0x7f010035
			public const int textAppearanceListItemSmall = 2130772021;
			
			// aapt resource value: 0x7f010031
			public const int textAppearanceSearchResultSubtitle = 2130772017;
			
			// aapt resource value: 0x7f010030
			public const int textAppearanceSearchResultTitle = 2130772016;
			
			// aapt resource value: 0x7f01001e
			public const int textAppearanceSmall = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int textAppearanceSmallPopupMenu = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int textColorPrimary = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int textColorPrimaryDisableOnly = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int textColorPrimaryInverse = 2130772001;
			
			// aapt resource value: 0x7f01002e
			public const int textColorSearchUrl = 2130772014;
			
			// aapt resource value: 0x7f01004a
			public const int title = 2130772042;
			
			// aapt resource value: 0x7f010000
			public const int titleTextStyle = 2130771968;
			
			// aapt resource value: 0x7f010057
			public const int verticalDivider = 2130772055;
			
			// aapt resource value: 0x7f010041
			public const int windowActionBar = 2130772033;
			
			// aapt resource value: 0x7f010042
			public const int windowActionBarOverlay = 2130772034;
			
			// aapt resource value: 0x7f010043
			public const int windowActionModeOverlay = 2130772035;
			
			// aapt resource value: 0x7f01005a
			public const int windowAnimationStyle = 2130772058;
			
			// aapt resource value: 0x7f01001b
			public const int windowContentOverlay = 2130771995;
			
			// aapt resource value: 0x7f010036
			public const int windowMinWidthMajor = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int windowMinWidthMinor = 2130772023;
			
			// aapt resource value: 0x7f010040
			public const int windowNoTitle = 2130772032;
			
			// aapt resource value: 0x7f010044
			public const int windowSplitActionBar = 2130772036;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int abs__action_bar_embed_tabs = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int abs__action_bar_expanded_action_views_exclusive = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int abs__config_actionMenuItemAllCaps = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abs__config_allowActionMenuItemTextWithIcon = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int abs__config_showMenuShortcutsWhenKeyboardPresent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int abs__split_action_bar_is_narrow = 2131034113;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int abs__background_holo_dark = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int abs__background_holo_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int abs__bright_foreground_disabled_holo_dark = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int abs__bright_foreground_disabled_holo_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int abs__bright_foreground_holo_dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int abs__bright_foreground_holo_light = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int abs__bright_foreground_inverse_holo_dark = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int abs__bright_foreground_inverse_holo_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int abs__holo_blue_light = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int abs__primary_text_disable_only_holo_dark = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int abs__primary_text_disable_only_holo_light = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int abs__primary_text_holo_dark = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int abs__primary_text_holo_light = 2131099660;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int abs__action_bar_default_height = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int abs__action_bar_icon_vertical_padding = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int abs__action_bar_subtitle_bottom_margin = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int abs__action_bar_subtitle_text_size = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int abs__action_bar_subtitle_top_margin = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int abs__action_bar_title_text_size = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int abs__action_button_min_width = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int abs__alert_dialog_title_height = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int abs__config_prefDialogWidth = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int abs__dialog_min_width_major = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int abs__dialog_min_width_minor = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int abs__dropdownitem_icon_width = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int abs__dropdownitem_text_padding_left = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int abs__dropdownitem_text_padding_right = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int abs__search_view_preferred_width = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int abs__search_view_text_min_width = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int action_button_min_width = 2131165200;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abs__ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abs__ab_bottom_solid_inverse_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abs__ab_bottom_solid_light_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abs__ab_bottom_transparent_dark_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abs__ab_bottom_transparent_light_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abs__ab_share_pack_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abs__ab_share_pack_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abs__ab_solid_dark_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abs__ab_solid_light_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abs__ab_solid_shadow_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abs__ab_stacked_solid_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abs__ab_stacked_solid_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abs__ab_stacked_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abs__ab_stacked_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abs__ab_transparent_dark_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abs__ab_transparent_light_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abs__activated_background_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abs__activated_background_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abs__btn_cab_done_default_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abs__btn_cab_done_default_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abs__btn_cab_done_focused_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abs__btn_cab_done_focused_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abs__btn_cab_done_holo_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abs__btn_cab_done_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abs__btn_cab_done_pressed_holo_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abs__btn_cab_done_pressed_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abs__cab_background_bottom_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abs__cab_background_bottom_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abs__cab_background_top_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abs__cab_background_top_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abs__dialog_full_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abs__dialog_full_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abs__ic_ab_back_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abs__ic_ab_back_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abs__ic_cab_done_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abs__ic_cab_done_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abs__ic_clear = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abs__ic_clear_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abs__ic_clear_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abs__ic_clear_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abs__ic_clear_search_api_disabled_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abs__ic_clear_search_api_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abs__ic_go = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abs__ic_go_search_api_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abs__ic_menu_moreoverflow_holo_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abs__ic_menu_moreoverflow_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abs__ic_menu_moreoverflow_normal_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abs__ic_menu_moreoverflow_normal_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abs__ic_menu_share_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abs__ic_menu_share_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abs__ic_search = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abs__ic_search_api_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abs__ic_voice_search = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abs__ic_voice_search_api_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abs__item_background_holo_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abs__item_background_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abs__list_activated_holo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abs__list_divider_holo_dark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abs__list_divider_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abs__list_focused_holo = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abs__list_longpressed_holo = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abs__list_pressed_holo_dark = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abs__list_pressed_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abs__list_selector_background_transition_holo_dark = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abs__list_selector_background_transition_holo_light = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abs__list_selector_disabled_holo_dark = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abs__list_selector_disabled_holo_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abs__list_selector_holo_dark = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abs__list_selector_holo_light = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abs__menu_dropdown_panel_holo_dark = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abs__menu_dropdown_panel_holo_light = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abs__progress_bg_holo_dark = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abs__progress_bg_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abs__progress_horizontal_holo_dark = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abs__progress_horizontal_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abs__progress_medium_holo = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abs__progress_primary_holo_dark = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abs__progress_primary_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abs__progress_secondary_holo_dark = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abs__progress_secondary_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abs__search_dropdown_dark = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abs__search_dropdown_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abs__spinner_48_inner_holo = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abs__spinner_48_outer_holo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abs__spinner_ab_default_holo_dark = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abs__spinner_ab_default_holo_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abs__spinner_ab_disabled_holo_dark = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int abs__spinner_ab_disabled_holo_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int abs__spinner_ab_focused_holo_dark = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int abs__spinner_ab_focused_holo_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int abs__spinner_ab_holo_dark = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int abs__spinner_ab_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int abs__spinner_ab_pressed_holo_dark = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int abs__spinner_ab_pressed_holo_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int abs__tab_indicator_ab_holo = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int abs__tab_selected_focused_holo = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int abs__tab_selected_holo = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int abs__tab_selected_pressed_holo = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int abs__tab_unselected_pressed_holo = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int abs__textfield_search_default_holo_dark = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int abs__textfield_search_default_holo_light = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int abs__textfield_search_right_default_holo_dark = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int abs__textfield_search_right_default_holo_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int abs__textfield_search_right_selected_holo_dark = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int abs__textfield_search_right_selected_holo_light = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int abs__textfield_search_selected_holo_dark = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int abs__textfield_search_selected_holo_light = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int abs__textfield_searchview_holo_dark = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int abs__textfield_searchview_holo_light = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int abs__textfield_searchview_right_holo_dark = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int abs__textfield_searchview_right_holo_light = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int Icon = 2130837615;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040022
			public const int abs__action_bar = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int abs__action_bar_container = 2130968609;
			
			// aapt resource value: 0x7f040011
			public const int abs__action_bar_subtitle = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int abs__action_bar_title = 2130968592;
			
			// aapt resource value: 0x7f040023
			public const int abs__action_context_bar = 2130968611;
			
			// aapt resource value: 0x7f04000c
			public const int abs__action_menu_divider = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int abs__action_menu_presenter = 2130968589;
			
			// aapt resource value: 0x7f040026
			public const int abs__action_mode_bar = 2130968614;
			
			// aapt resource value: 0x7f040025
			public const int abs__action_mode_bar_stub = 2130968613;
			
			// aapt resource value: 0x7f040014
			public const int abs__action_mode_close_button = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int abs__activity_chooser_view_content = 2130968597;
			
			// aapt resource value: 0x7f04001e
			public const int abs__checkbox = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int abs__content = 2130968605;
			
			// aapt resource value: 0x7f040018
			public const int abs__default_activity_button = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int abs__expand_activities_button = 2130968598;
			
			// aapt resource value: 0x7f04000a
			public const int abs__home = 2130968586;
			
			// aapt resource value: 0x7f04001a
			public const int abs__icon = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int abs__image = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int abs__imageButton = 2130968594;
			
			// aapt resource value: 0x7f040019
			public const int abs__list_item = 2130968601;
			
			// aapt resource value: 0x7f04000e
			public const int abs__progress_circular = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int abs__progress_horizontal = 2130968591;
			
			// aapt resource value: 0x7f040020
			public const int abs__radio = 2130968608;
			
			// aapt resource value: 0x7f040029
			public const int abs__search_badge = 2130968617;
			
			// aapt resource value: 0x7f040028
			public const int abs__search_bar = 2130968616;
			
			// aapt resource value: 0x7f04002a
			public const int abs__search_button = 2130968618;
			
			// aapt resource value: 0x7f04002f
			public const int abs__search_close_btn = 2130968623;
			
			// aapt resource value: 0x7f04002b
			public const int abs__search_edit_frame = 2130968619;
			
			// aapt resource value: 0x7f040031
			public const int abs__search_go_btn = 2130968625;
			
			// aapt resource value: 0x7f04002c
			public const int abs__search_mag_icon = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int abs__search_plate = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int abs__search_src_text = 2130968622;
			
			// aapt resource value: 0x7f040032
			public const int abs__search_voice_btn = 2130968626;
			
			// aapt resource value: 0x7f04001f
			public const int abs__shortcut = 2130968607;
			
			// aapt resource value: 0x7f040024
			public const int abs__split_action_bar = 2130968612;
			
			// aapt resource value: 0x7f040030
			public const int abs__submit_area = 2130968624;
			
			// aapt resource value: 0x7f040013
			public const int abs__textButton = 2130968595;
			
			// aapt resource value: 0x7f04001b
			public const int abs__title = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int abs__titleDivider = 2130968604;
			
			// aapt resource value: 0x7f04000b
			public const int abs__up = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int disableHome = 2130968585;
			
			// aapt resource value: 0x7f040027
			public const int edit_query = 2130968615;
			
			// aapt resource value: 0x7f040006
			public const int homeAsUp = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int listMode = 2130968578;
			
			// aapt resource value: 0x7f040033
			public const int myButton = 2130968627;
			
			// aapt resource value: 0x7f040001
			public const int normal = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int showCustom = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int showHome = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int showTitle = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int tabMode = 2130968579;
			
			// aapt resource value: 0x7f040034
			public const int textView1 = 2130968628;
			
			// aapt resource value: 0x7f040004
			public const int useLogo = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int wrap_content = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int abs__max_action_buttons = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int abs__action_bar_home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int abs__action_bar_tab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int abs__action_bar_tab_bar_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int abs__action_bar_title_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int abs__action_menu_item_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int abs__action_menu_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int abs__action_mode_bar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int abs__action_mode_close_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int abs__activity_chooser_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int abs__activity_chooser_view_list_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int abs__dialog_title_holo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int abs__list_menu_item_checkbox = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int abs__list_menu_item_icon = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int abs__list_menu_item_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int abs__list_menu_item_radio = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int abs__popup_menu_item_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int abs__screen_action_bar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int abs__screen_action_bar_overlay = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int abs__screen_simple = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int abs__screen_simple_overlay_action_mode = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int abs__search_dropdown_item_icons_2line = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int abs__search_view = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int abs__simple_dropdown_hint = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Main = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Secondary = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int sherlock_spinner_dropdown_item = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int sherlock_spinner_item = 2130903066;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090000
			public const int abs__action_bar_home_description = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int abs__action_bar_up_description = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int abs__action_menu_overflow_description = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int abs__action_mode_done = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int abs__activity_chooser_view_dialog_title_default = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int abs__activity_chooser_view_see_all = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int abs__activitychooserview_choose_application = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int abs__searchview_description_clear = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int abs__searchview_description_query = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int abs__searchview_description_search = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int abs__searchview_description_submit = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int abs__searchview_description_voice = 2131296270;
			
			// aapt resource value: 0x7f090006
			public const int abs__share_action_provider_share_with = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int abs__shareactionprovider_share_with = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int abs__shareactionprovider_share_with_application = 2131296265;
			
			// aapt resource value: 0x7f090010
			public const int app_name = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int hello = 2131296271;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0036
			public const int DialogWindowTitle_Sherlock = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int DialogWindowTitle_Sherlock_Light = 2131361847;
			
			// aapt resource value: 0x7f0a004a
			public const int Sherlock___TextAppearance_Small = 2131361866;
			
			// aapt resource value: 0x7f0a004e
			public const int Sherlock___Theme = 2131361870;
			
			// aapt resource value: 0x7f0a0050
			public const int Sherlock___Theme_DarkActionBar = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int Sherlock___Theme_Dialog = 2131361873;
			
			// aapt resource value: 0x7f0a004f
			public const int Sherlock___Theme_Light = 2131361871;
			
			// aapt resource value: 0x7f0a0001
			public const int Sherlock___Widget_ActionBar = 2131361793;
			
			// aapt resource value: 0x7f0a0016
			public const int Sherlock___Widget_ActionMode = 2131361814;
			
			// aapt resource value: 0x7f0a001e
			public const int Sherlock___Widget_ActivityChooserView = 2131361822;
			
			// aapt resource value: 0x7f0a0029
			public const int Sherlock___Widget_Holo_DropDownItem = 2131361833;
			
			// aapt resource value: 0x7f0a0026
			public const int Sherlock___Widget_Holo_ListView = 2131361830;
			
			// aapt resource value: 0x7f0a0023
			public const int Sherlock___Widget_Holo_Spinner = 2131361827;
			
			// aapt resource value: 0x7f0a0033
			public const int Sherlock___Widget_SearchAutoCompleteTextView = 2131361843;
			
			// aapt resource value: 0x7f0a0048
			public const int TextAppearance_Sherlock_DialogWindowTitle = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int TextAppearance_Sherlock_Light_DialogWindowTitle = 2131361865;
			
			// aapt resource value: 0x7f0a004c
			public const int TextAppearance_Sherlock_Light_Small = 2131361868;
			
			// aapt resource value: 0x7f0a0043
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Large = 2131361859;
			
			// aapt resource value: 0x7f0a0045
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Small = 2131361861;
			
			// aapt resource value: 0x7f0a004b
			public const int TextAppearance_Sherlock_Small = 2131361867;
			
			// aapt resource value: 0x7f0a0038
			public const int TextAppearance_Sherlock_Widget_ActionBar_Menu = 2131361848;
			
			// aapt resource value: 0x7f0a003b
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle_Inverse = 2131361852;
			
			// aapt resource value: 0x7f0a0039
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title_Inverse = 2131361850;
			
			// aapt resource value: 0x7f0a003f
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse = 2131361856;
			
			// aapt resource value: 0x7f0a003d
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title_Inverse = 2131361854;
			
			// aapt resource value: 0x7f0a004d
			public const int TextAppearance_Sherlock_Widget_DropDownHint = 2131361869;
			
			// aapt resource value: 0x7f0a0047
			public const int TextAppearance_Sherlock_Widget_DropDownItem = 2131361863;
			
			// aapt resource value: 0x7f0a0041
			public const int TextAppearance_Sherlock_Widget_PopupMenu = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Large = 2131361858;
			
			// aapt resource value: 0x7f0a0044
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Small = 2131361860;
			
			// aapt resource value: 0x7f0a0046
			public const int TextAppearance_Sherlock_Widget_TextView_SpinnerItem = 2131361862;
			
			// aapt resource value: 0x7f0a0052
			public const int Theme_Sherlock = 2131361874;
			
			// aapt resource value: 0x7f0a0057
			public const int Theme_Sherlock_Dialog = 2131361879;
			
			// aapt resource value: 0x7f0a0053
			public const int Theme_Sherlock_Light = 2131361875;
			
			// aapt resource value: 0x7f0a0054
			public const int Theme_Sherlock_Light_DarkActionBar = 2131361876;
			
			// aapt resource value: 0x7f0a0058
			public const int Theme_Sherlock_Light_Dialog = 2131361880;
			
			// aapt resource value: 0x7f0a0056
			public const int Theme_Sherlock_Light_NoActionBar = 2131361878;
			
			// aapt resource value: 0x7f0a0055
			public const int Theme_Sherlock_NoActionBar = 2131361877;
			
			// aapt resource value: 0x7f0a0000
			public const int Widget = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int Widget_Sherlock_ActionBar = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int Widget_Sherlock_ActionBar_Solid = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int Widget_Sherlock_ActionBar_TabBar = 2131361802;
			
			// aapt resource value: 0x7f0a000d
			public const int Widget_Sherlock_ActionBar_TabText = 2131361805;
			
			// aapt resource value: 0x7f0a0007
			public const int Widget_Sherlock_ActionBar_TabView = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int Widget_Sherlock_ActionButton = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int Widget_Sherlock_ActionButton_CloseMode = 2131361810;
			
			// aapt resource value: 0x7f0a0014
			public const int Widget_Sherlock_ActionButton_Overflow = 2131361812;
			
			// aapt resource value: 0x7f0a0017
			public const int Widget_Sherlock_ActionMode = 2131361815;
			
			// aapt resource value: 0x7f0a001f
			public const int Widget_Sherlock_ActivityChooserView = 2131361823;
			
			// aapt resource value: 0x7f0a0021
			public const int Widget_Sherlock_Button_Small = 2131361825;
			
			// aapt resource value: 0x7f0a002a
			public const int Widget_Sherlock_DropDownItem_Spinner = 2131361834;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_Sherlock_Light_ActionBar = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int Widget_Sherlock_Light_ActionBar_Solid = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int Widget_Sherlock_Light_ActionBar_Solid_Inverse = 2131361798;
			
			// aapt resource value: 0x7f0a000b
			public const int Widget_Sherlock_Light_ActionBar_TabBar = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int Widget_Sherlock_Light_ActionBar_TabBar_Inverse = 2131361804;
			
			// aapt resource value: 0x7f0a000e
			public const int Widget_Sherlock_Light_ActionBar_TabText = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int Widget_Sherlock_Light_ActionBar_TabText_Inverse = 2131361807;
			
			// aapt resource value: 0x7f0a0008
			public const int Widget_Sherlock_Light_ActionBar_TabView = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int Widget_Sherlock_Light_ActionBar_TabView_Inverse = 2131361801;
			
			// aapt resource value: 0x7f0a0011
			public const int Widget_Sherlock_Light_ActionButton = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int Widget_Sherlock_Light_ActionButton_CloseMode = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int Widget_Sherlock_Light_ActionButton_Overflow = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int Widget_Sherlock_Light_ActionMode = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int Widget_Sherlock_Light_ActionMode_Inverse = 2131361817;
			
			// aapt resource value: 0x7f0a0020
			public const int Widget_Sherlock_Light_ActivityChooserView = 2131361824;
			
			// aapt resource value: 0x7f0a0022
			public const int Widget_Sherlock_Light_Button_Small = 2131361826;
			
			// aapt resource value: 0x7f0a002b
			public const int Widget_Sherlock_Light_DropDownItem_Spinner = 2131361835;
			
			// aapt resource value: 0x7f0a001b
			public const int Widget_Sherlock_Light_ListPopupWindow = 2131361819;
			
			// aapt resource value: 0x7f0a0028
			public const int Widget_Sherlock_Light_ListView_DropDown = 2131361832;
			
			// aapt resource value: 0x7f0a001d
			public const int Widget_Sherlock_Light_PopupMenu = 2131361821;
			
			// aapt resource value: 0x7f0a002d
			public const int Widget_Sherlock_Light_PopupWindow_ActionMode = 2131361837;
			
			// aapt resource value: 0x7f0a002f
			public const int Widget_Sherlock_Light_ProgressBar = 2131361839;
			
			// aapt resource value: 0x7f0a0031
			public const int Widget_Sherlock_Light_ProgressBar_Horizontal = 2131361841;
			
			// aapt resource value: 0x7f0a0035
			public const int Widget_Sherlock_Light_SearchAutoCompleteTextView = 2131361845;
			
			// aapt resource value: 0x7f0a0025
			public const int Widget_Sherlock_Light_Spinner_DropDown_ActionBar = 2131361829;
			
			// aapt resource value: 0x7f0a001a
			public const int Widget_Sherlock_ListPopupWindow = 2131361818;
			
			// aapt resource value: 0x7f0a0027
			public const int Widget_Sherlock_ListView_DropDown = 2131361831;
			
			// aapt resource value: 0x7f0a001c
			public const int Widget_Sherlock_PopupMenu = 2131361820;
			
			// aapt resource value: 0x7f0a002c
			public const int Widget_Sherlock_PopupWindow_ActionMode = 2131361836;
			
			// aapt resource value: 0x7f0a002e
			public const int Widget_Sherlock_ProgressBar = 2131361838;
			
			// aapt resource value: 0x7f0a0030
			public const int Widget_Sherlock_ProgressBar_Horizontal = 2131361840;
			
			// aapt resource value: 0x7f0a0034
			public const int Widget_Sherlock_SearchAutoCompleteTextView = 2131361844;
			
			// aapt resource value: 0x7f0a0024
			public const int Widget_Sherlock_Spinner_DropDown_ActionBar = 2131361828;
			
			// aapt resource value: 0x7f0a0032
			public const int Widget_Sherlock_TextView_SpinnerItem = 2131361842;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SherlockActionBar = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052};
			
			// aapt resource value: 2
			public const int SherlockActionBar_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionBar_backgroundSplit = 3;
			
			// aapt resource value: 12
			public const int SherlockActionBar_backgroundStacked = 12;
			
			// aapt resource value: 13
			public const int SherlockActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 7
			public const int SherlockActionBar_displayOptions = 7;
			
			// aapt resource value: 5
			public const int SherlockActionBar_divider = 5;
			
			// aapt resource value: 4
			public const int SherlockActionBar_height = 4;
			
			// aapt resource value: 14
			public const int SherlockActionBar_homeLayout = 14;
			
			// aapt resource value: 10
			public const int SherlockActionBar_icon = 10;
			
			// aapt resource value: 16
			public const int SherlockActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int SherlockActionBar_itemPadding = 18;
			
			// aapt resource value: 11
			public const int SherlockActionBar_logo = 11;
			
			// aapt resource value: 6
			public const int SherlockActionBar_navigationMode = 6;
			
			// aapt resource value: 17
			public const int SherlockActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int SherlockActionBar_progressBarStyle = 15;
			
			// aapt resource value: 9
			public const int SherlockActionBar_subtitle = 9;
			
			// aapt resource value: 1
			public const int SherlockActionBar_subtitleTextStyle = 1;
			
			// aapt resource value: 8
			public const int SherlockActionBar_title = 8;
			
			// aapt resource value: 0
			public const int SherlockActionBar_titleTextStyle = 0;
			
			public static int[] SherlockActionMenuItemView = new int[]
			{
					16843071};
			
			// aapt resource value: 0
			public const int SherlockActionMenuItemView_android_minWidth = 0;
			
			public static int[] SherlockActionMode = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int SherlockActionMode_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionMode_backgroundSplit = 3;
			
			// aapt resource value: 4
			public const int SherlockActionMode_height = 4;
			
			// aapt resource value: 1
			public const int SherlockActionMode_subtitleTextStyle = 1;
			
			// aapt resource value: 0
			public const int SherlockActionMode_titleTextStyle = 0;
			
			public static int[] SherlockActivityChooserView = new int[]
			{
					16842964,
					2130772061,
					2130772062};
			
			// aapt resource value: 0
			public const int SherlockActivityChooserView_android_background = 0;
			
			// aapt resource value: 2
			public const int SherlockActivityChooserView_expandActivityOverflowButtonDrawable = 2;
			
			// aapt resource value: 1
			public const int SherlockActivityChooserView_initialActivityCount = 1;
			
			public static int[] SherlockMenuGroup = new int[]
			{
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int SherlockMenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int SherlockMenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int SherlockMenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int SherlockMenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int SherlockMenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int SherlockMenuGroup_android_visible = 2;
			
			public static int[] SherlockMenuItem = new int[]
			{
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					16843481,
					16843515,
					16843516,
					16843657};
			
			// aapt resource value: 14
			public const int SherlockMenuItem_android_actionLayout = 14;
			
			// aapt resource value: 16
			public const int SherlockMenuItem_android_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int SherlockMenuItem_android_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int SherlockMenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int SherlockMenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int SherlockMenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int SherlockMenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int SherlockMenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int SherlockMenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int SherlockMenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int SherlockMenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 13
			public const int SherlockMenuItem_android_showAsAction = 13;
			
			// aapt resource value: 7
			public const int SherlockMenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int SherlockMenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int SherlockMenuItem_android_visible = 4;
			
			public static int[] SherlockMenuView = new int[]
			{
					2130772053,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060};
			
			// aapt resource value: 3
			public const int SherlockMenuView_headerBackground = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuView_horizontalDivider = 1;
			
			// aapt resource value: 4
			public const int SherlockMenuView_itemBackground = 4;
			
			// aapt resource value: 6
			public const int SherlockMenuView_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 0
			public const int SherlockMenuView_itemTextAppearance = 0;
			
			// aapt resource value: 7
			public const int SherlockMenuView_preserveIconSpacing = 7;
			
			// aapt resource value: 2
			public const int SherlockMenuView_verticalDivider = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuView_windowAnimationStyle = 5;
			
			public static int[] SherlockSearchView = new int[]
			{
					16843039,
					16843296,
					16843364,
					2130772063,
					2130772064};
			
			// aapt resource value: 2
			public const int SherlockSearchView_android_imeOptions = 2;
			
			// aapt resource value: 1
			public const int SherlockSearchView_android_inputType = 1;
			
			// aapt resource value: 0
			public const int SherlockSearchView_android_maxWidth = 0;
			
			// aapt resource value: 3
			public const int SherlockSearchView_iconifiedByDefault = 3;
			
			// aapt resource value: 4
			public const int SherlockSearchView_queryHint = 4;
			
			public static int[] SherlockSpinner = new int[]
			{
					16842927,
					16843125,
					16843126,
					16843131,
					16843362,
					16843436,
					16843437,
					16843759};
			
			// aapt resource value: 5
			public const int SherlockSpinner_android_dropDownHorizontalOffset = 5;
			
			// aapt resource value: 1
			public const int SherlockSpinner_android_dropDownSelector = 1;
			
			// aapt resource value: 6
			public const int SherlockSpinner_android_dropDownVerticalOffset = 6;
			
			// aapt resource value: 4
			public const int SherlockSpinner_android_dropDownWidth = 4;
			
			// aapt resource value: 0
			public const int SherlockSpinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int SherlockSpinner_android_popupBackground = 2;
			
			// aapt resource value: 7
			public const int SherlockSpinner_android_popupPromptView = 7;
			
			// aapt resource value: 3
			public const int SherlockSpinner_android_prompt = 3;
			
			public static int[] SherlockTheme = new int[]
			{
					16842839,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039};
			
			// aapt resource value: 9
			public const int SherlockTheme_actionBarDivider = 9;
			
			// aapt resource value: 10
			public const int SherlockTheme_actionBarItemBackground = 10;
			
			// aapt resource value: 8
			public const int SherlockTheme_actionBarSize = 8;
			
			// aapt resource value: 6
			public const int SherlockTheme_actionBarSplitStyle = 6;
			
			// aapt resource value: 5
			public const int SherlockTheme_actionBarStyle = 5;
			
			// aapt resource value: 2
			public const int SherlockTheme_actionBarTabBarStyle = 2;
			
			// aapt resource value: 1
			public const int SherlockTheme_actionBarTabStyle = 1;
			
			// aapt resource value: 3
			public const int SherlockTheme_actionBarTabTextStyle = 3;
			
			// aapt resource value: 7
			public const int SherlockTheme_actionBarWidgetTheme = 7;
			
			// aapt resource value: 53
			public const int SherlockTheme_actionButtonStyle = 53;
			
			// aapt resource value: 52
			public const int SherlockTheme_actionDropDownStyle = 52;
			
			// aapt resource value: 11
			public const int SherlockTheme_actionMenuTextAppearance = 11;
			
			// aapt resource value: 12
			public const int SherlockTheme_actionMenuTextColor = 12;
			
			// aapt resource value: 15
			public const int SherlockTheme_actionModeBackground = 15;
			
			// aapt resource value: 14
			public const int SherlockTheme_actionModeCloseButtonStyle = 14;
			
			// aapt resource value: 17
			public const int SherlockTheme_actionModeCloseDrawable = 17;
			
			// aapt resource value: 19
			public const int SherlockTheme_actionModePopupWindowStyle = 19;
			
			// aapt resource value: 18
			public const int SherlockTheme_actionModeShareDrawable = 18;
			
			// aapt resource value: 16
			public const int SherlockTheme_actionModeSplitBackground = 16;
			
			// aapt resource value: 13
			public const int SherlockTheme_actionModeStyle = 13;
			
			// aapt resource value: 4
			public const int SherlockTheme_actionOverflowButtonStyle = 4;
			
			// aapt resource value: 58
			public const int SherlockTheme_actionSpinnerItemStyle = 58;
			
			// aapt resource value: 66
			public const int SherlockTheme_activatedBackgroundIndicator = 66;
			
			// aapt resource value: 65
			public const int SherlockTheme_activityChooserViewStyle = 65;
			
			// aapt resource value: 0
			public const int SherlockTheme_android_windowIsFloating = 0;
			
			// aapt resource value: 20
			public const int SherlockTheme_buttonStyleSmall = 20;
			
			// aapt resource value: 51
			public const int SherlockTheme_dividerVertical = 51;
			
			// aapt resource value: 55
			public const int SherlockTheme_dropDownListViewStyle = 55;
			
			// aapt resource value: 57
			public const int SherlockTheme_dropdownListPreferredItemHeight = 57;
			
			// aapt resource value: 54
			public const int SherlockTheme_homeAsUpIndicator = 54;
			
			// aapt resource value: 64
			public const int SherlockTheme_listPopupWindowStyle = 64;
			
			// aapt resource value: 45
			public const int SherlockTheme_listPreferredItemHeightSmall = 45;
			
			// aapt resource value: 46
			public const int SherlockTheme_listPreferredItemPaddingLeft = 46;
			
			// aapt resource value: 47
			public const int SherlockTheme_listPreferredItemPaddingRight = 47;
			
			// aapt resource value: 56
			public const int SherlockTheme_popupMenuStyle = 56;
			
			// aapt resource value: 31
			public const int SherlockTheme_searchAutoCompleteTextView = 31;
			
			// aapt resource value: 32
			public const int SherlockTheme_searchDropdownBackground = 32;
			
			// aapt resource value: 42
			public const int SherlockTheme_searchResultListItemHeight = 42;
			
			// aapt resource value: 33
			public const int SherlockTheme_searchViewCloseIcon = 33;
			
			// aapt resource value: 37
			public const int SherlockTheme_searchViewEditQuery = 37;
			
			// aapt resource value: 38
			public const int SherlockTheme_searchViewEditQueryBackground = 38;
			
			// aapt resource value: 34
			public const int SherlockTheme_searchViewGoIcon = 34;
			
			// aapt resource value: 35
			public const int SherlockTheme_searchViewSearchIcon = 35;
			
			// aapt resource value: 39
			public const int SherlockTheme_searchViewTextField = 39;
			
			// aapt resource value: 40
			public const int SherlockTheme_searchViewTextFieldRight = 40;
			
			// aapt resource value: 36
			public const int SherlockTheme_searchViewVoiceIcon = 36;
			
			// aapt resource value: 21
			public const int SherlockTheme_selectableItemBackground = 21;
			
			// aapt resource value: 30
			public const int SherlockTheme_spinnerDropDownItemStyle = 30;
			
			// aapt resource value: 29
			public const int SherlockTheme_spinnerItemStyle = 29;
			
			// aapt resource value: 23
			public const int SherlockTheme_textAppearanceLargePopupMenu = 23;
			
			// aapt resource value: 48
			public const int SherlockTheme_textAppearanceListItemSmall = 48;
			
			// aapt resource value: 44
			public const int SherlockTheme_textAppearanceSearchResultSubtitle = 44;
			
			// aapt resource value: 43
			public const int SherlockTheme_textAppearanceSearchResultTitle = 43;
			
			// aapt resource value: 25
			public const int SherlockTheme_textAppearanceSmall = 25;
			
			// aapt resource value: 24
			public const int SherlockTheme_textAppearanceSmallPopupMenu = 24;
			
			// aapt resource value: 26
			public const int SherlockTheme_textColorPrimary = 26;
			
			// aapt resource value: 27
			public const int SherlockTheme_textColorPrimaryDisableOnly = 27;
			
			// aapt resource value: 28
			public const int SherlockTheme_textColorPrimaryInverse = 28;
			
			// aapt resource value: 41
			public const int SherlockTheme_textColorSearchUrl = 41;
			
			// aapt resource value: 60
			public const int SherlockTheme_windowActionBar = 60;
			
			// aapt resource value: 61
			public const int SherlockTheme_windowActionBarOverlay = 61;
			
			// aapt resource value: 62
			public const int SherlockTheme_windowActionModeOverlay = 62;
			
			// aapt resource value: 22
			public const int SherlockTheme_windowContentOverlay = 22;
			
			// aapt resource value: 49
			public const int SherlockTheme_windowMinWidthMajor = 49;
			
			// aapt resource value: 50
			public const int SherlockTheme_windowMinWidthMinor = 50;
			
			// aapt resource value: 59
			public const int SherlockTheme_windowNoTitle = 59;
			
			// aapt resource value: 63
			public const int SherlockTheme_windowSplitActionBar = 63;
			
			public static int[] SherlockView = new int[]
			{
					16842970};
			
			// aapt resource value: 0
			public const int SherlockView_android_focusable = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
