<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(ReactiveUITestingUITargets)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WinUI\**\*.cs"/>
    <None Include="WinUI\**\*.cs"/>
    <ProjectReference Include="..\ReactiveUI.Test.Utilities\ReactiveUI.Test.Utilities.csproj"/>
  </ItemGroup>

  <Choose>
    <When Condition="$(TargetFramework.EndsWith('-windows10.0.19041.0'))">
      <PropertyGroup>
        <UseWinUI>true</UseWinUI>
        <WindowsPackageType>None</WindowsPackageType>
        <GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
        <PublishAppxPackage>false</PublishAppxPackage>
        <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
      </PropertyGroup>
      <ItemGroup>
        <Compile Remove="WinUIFallbackTest.cs"/>
        <ProjectReference Include="..\..\ReactiveUI.WinUI\ReactiveUI.WinUI.csproj"/>
        <Compile Include="WinUI\**\*.cs"/>
      </ItemGroup>
    </When>
  </Choose>

  <Import Project="..\..\ReactiveUI.WinUI\build\SkipMakePriOnNonWindows.targets"
          Condition="!$([MSBuild]::IsOsPlatform('Windows')) and $(TargetFramework.EndsWith('-windows10.0.19041.0'))"/>
</Project>
