#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReactiveUI.Tests.Resource", IsApplication=true)]

namespace ReactiveUI.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::ReactiveUI.Tests.Resource.String.library_name;
			global::Xunit.Runners.Resource.Drawable.dialog_disclosure = global::ReactiveUI.Tests.Resource.Drawable.dialog_disclosure;
			global::Xunit.Runners.Resource.Drawable.dialog_expander_ic_minimized = global::ReactiveUI.Tests.Resource.Drawable.dialog_expander_ic_minimized;
			global::Xunit.Runners.Resource.Id.dialog_BoolField = global::ReactiveUI.Tests.Resource.Id.dialog_BoolField;
			global::Xunit.Runners.Resource.Id.dialog_Button = global::ReactiveUI.Tests.Resource.Id.dialog_Button;
			global::Xunit.Runners.Resource.Id.dialog_DisclosureField = global::ReactiveUI.Tests.Resource.Id.dialog_DisclosureField;
			global::Xunit.Runners.Resource.Id.dialog_ImageLeft = global::ReactiveUI.Tests.Resource.Id.dialog_ImageLeft;
			global::Xunit.Runners.Resource.Id.dialog_ImageRight = global::ReactiveUI.Tests.Resource.Id.dialog_ImageRight;
			global::Xunit.Runners.Resource.Id.dialog_LabelField = global::ReactiveUI.Tests.Resource.Id.dialog_LabelField;
			global::Xunit.Runners.Resource.Id.dialog_LabelSubtextField = global::ReactiveUI.Tests.Resource.Id.dialog_LabelSubtextField;
			global::Xunit.Runners.Resource.Id.dialog_Panel = global::ReactiveUI.Tests.Resource.Id.dialog_Panel;
			global::Xunit.Runners.Resource.Id.dialog_RadioButtonList = global::ReactiveUI.Tests.Resource.Id.dialog_RadioButtonList;
			global::Xunit.Runners.Resource.Id.dialog_SliderField = global::ReactiveUI.Tests.Resource.Id.dialog_SliderField;
			global::Xunit.Runners.Resource.Id.dialog_Spinner = global::ReactiveUI.Tests.Resource.Id.dialog_Spinner;
			global::Xunit.Runners.Resource.Id.dialog_ValueField = global::ReactiveUI.Tests.Resource.Id.dialog_ValueField;
			global::Xunit.Runners.Resource.Id.iFormFieldValue = global::ReactiveUI.Tests.Resource.Id.iFormFieldValue;
			global::Xunit.Runners.Resource.Layout.dialog_achievements = global::ReactiveUI.Tests.Resource.Layout.dialog_achievements;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldleft = global::ReactiveUI.Tests.Resource.Layout.dialog_boolfieldleft;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldright = global::ReactiveUI.Tests.Resource.Layout.dialog_boolfieldright;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldsubleft = global::ReactiveUI.Tests.Resource.Layout.dialog_boolfieldsubleft;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldsubright = global::ReactiveUI.Tests.Resource.Layout.dialog_boolfieldsubright;
			global::Xunit.Runners.Resource.Layout.dialog_button = global::ReactiveUI.Tests.Resource.Layout.dialog_button;
			global::Xunit.Runners.Resource.Layout.dialog_datefield = global::ReactiveUI.Tests.Resource.Layout.dialog_datefield;
			global::Xunit.Runners.Resource.Layout.dialog_fieldsetlabel = global::ReactiveUI.Tests.Resource.Layout.dialog_fieldsetlabel;
			global::Xunit.Runners.Resource.Layout.dialog_floatimage = global::ReactiveUI.Tests.Resource.Layout.dialog_floatimage;
			global::Xunit.Runners.Resource.Layout.dialog_labelfieldbelow = global::ReactiveUI.Tests.Resource.Layout.dialog_labelfieldbelow;
			global::Xunit.Runners.Resource.Layout.dialog_labelfieldright = global::ReactiveUI.Tests.Resource.Layout.dialog_labelfieldright;
			global::Xunit.Runners.Resource.Layout.dialog_onofffieldright = global::ReactiveUI.Tests.Resource.Layout.dialog_onofffieldright;
			global::Xunit.Runners.Resource.Layout.dialog_panel = global::ReactiveUI.Tests.Resource.Layout.dialog_panel;
			global::Xunit.Runners.Resource.Layout.dialog_root = global::ReactiveUI.Tests.Resource.Layout.dialog_root;
			global::Xunit.Runners.Resource.Layout.dialog_selectlist = global::ReactiveUI.Tests.Resource.Layout.dialog_selectlist;
			global::Xunit.Runners.Resource.Layout.dialog_selectlistfield = global::ReactiveUI.Tests.Resource.Layout.dialog_selectlistfield;
			global::Xunit.Runners.Resource.Layout.dialog_textarea = global::ReactiveUI.Tests.Resource.Layout.dialog_textarea;
			global::Xunit.Runners.Resource.Layout.dialog_textfieldbelow = global::ReactiveUI.Tests.Resource.Layout.dialog_textfieldbelow;
			global::Xunit.Runners.Resource.Layout.dialog_textfieldright = global::ReactiveUI.Tests.Resource.Layout.dialog_textfieldright;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int dialog_BoolField = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int dialog_Button = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int dialog_DisclosureField = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int dialog_ImageLeft = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int dialog_ImageRight = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int dialog_LabelField = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int dialog_LabelSubtextField = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int dialog_Panel = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_RadioButtonList = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int dialog_SliderField = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_Spinner = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int dialog_ValueField = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int iFormFieldValue = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int myButton = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldbelow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_onofffieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_root = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_selectlist = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_selectlistfield = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textarea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_textfieldbelow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textfieldright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
