#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileSample_Android.Resource", IsApplication=true)]

namespace MobileSample_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::MobileSample_Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int SavedGuid = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int closeMarket = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int high = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int lastChange = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int low = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int open = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int openMarket = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int percentChange = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int price = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int reset = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int symbol = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int watchList = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Secondary = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int WatchList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WatchListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
