site_name: ReactiveUI Documentation
#site_url: http://docs.reactiveui.net/
site_url: /
site_description: Documentation for fast and lightweight ReactiveUI container based virtualization framework.
site_favicon: img/favicon.png

dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/reactiveui/reactiveui/

docs_dir: sources

include_search: true

use_absolute_urls: true

# theme: ReactiveUI
#theme_dir: ./theme/mkdocs/
#theme_center_lead: false

copyright: Copyright &copy; 2014, ReactiveUI, Inc.
google_analytics: ['UA-6096819-11', 'ReactiveUI.io']

pages:

# Introduction:
- ['index.md', 'About', 'ReactiveUI']
- ['release-notes.md', 'About', 'Release Notes']
#- ['introduction/index.md', '**HIDDEN**']
#- ['introduction/understanding-ReactiveUI.md', 'About', 'Understanding ReactiveUI']

# - ['static_files/README.md', 'static_files', 'README']
#- ['terms/index.md', '**HIDDEN**']
#- ['terms/layer.md', '**HIDDEN**']
#- ['terms/index.md', '**HIDDEN**']
#- ['terms/registry.md', '**HIDDEN**']
#- ['terms/container.md', '**HIDDEN**']
#- ['terms/repository.md', '**HIDDEN**']
#- ['terms/filesystem.md', '**HIDDEN**']
#- ['terms/image.md', '**HIDDEN**']

# Contribute:
#- ['contributing/index.md', '**HIDDEN**']
#- ['contributing/contributing.md', 'Contribute', 'Contributing']
#- ['contributing/devenvironment.md', 'Contribute', 'Development environment']
#- ['contributing/docs_style-guide.md', 'Contribute', 'Documentation style guide']
