name: Device Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  device-tests:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-device-tests.yml@main
    with:
      projects: src/tests/ReactiveUI.Device.Tests/ReactiveUI.Device.Tests.csproj
      configuration: Release
      solutionFile: reactiveui.slnx
